# Generated by Django 6.0.3 on 2026-06-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0006_merge_20260601_1214'),
    ]

    operations = [
    ]
