# Generated by Codex to reconcile duplicate blood_requests merge leaves.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0006_merge_20260601_1214"),
        ("blood_requests", "0006_merge_20260601_1830"),
    ]

    operations = []
