# Generated by Codex to cap chat message length.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0007_merge_20260611_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.CharField(max_length=2000),
        ),
    ]
